version: '3.8'


services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: uvicorn --reload --host 0.0.0.0 --port 8000 app.main:app
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.dev
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    command: npm run start
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  redis:
    image: redis
  dramatiq:
    build:
      context: ./backend
      dockerfile: dramatiq.dockerfile
    command: dramatiq app.core.dramatiq:redis_broker app.utils.dramatiq.actors -v --watch app/
    volumes:
      - ./backend/app:/app
    depends_on:
      - backend
      - redis
    env_file:
      - ./.env.dev
volumes:
  postgres_data:
