"""additional_takedown_actions

Revision ID: 29708b56cd27
Revises: 03e4a10e2a4c
Create Date: 2021-03-03 17:03:54.087390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29708b56cd27'
down_revision = '03e4a10e2a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('additional_takedown_actions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'additional_takedown_actions')
    # ### end Alembic commands ###
